layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba32f, binding=0) uniform readonly image2D litMap;
layout(rgba32f, binding=1) uniform writeonly image2D bloomMap;

void main() {
    ivec2 texturePos = ivec2(gl_GlobalInvocationID.xy);
    vec4 inColor = imageLoad(litMap, texturePos);

    vec4 brightColor = inColor * 0.2;
    brightColor *= brightColor;
    imageStore(bloomMap, texturePos, brightColor);
}
